service: middytest
frameworkVersion: '3'

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:PROFILE}
  region: eu-north-1
  iam:
    role: ${env:LAMBDA_ROLE}
  deploymentMethod: direct
  environment:
    TABLE_NAME: middyTest

  useDotenv: true

functions:
  createUser:
    handler: src/functions/createUser.handler
    events:
      - httpApi:
          path: '/api/user'
          method: POST
  updateUser:
    handler: src/functions/updateUser.handler
    events:
      - httpApi:
          path: '/api/user'
          method: PATCH
  deleteUser:
    handler: src/functions/deleteUser.handler
    events:
      - httpApi:
          path: '/api/user/{id}'
          method: DELETE
  getUser:
    handler: src/functions/getUser.handler
    events:
      - httpApi:
          path: '/api/user/{id}'
          method: GET
  getAllUsers:
    handler: src/functions/getAllUsers.handler
    events:
      - httpApi:
          path: '/api/users'
          method: GET

resources:
  Resources:
    MiddyDatabase:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST